# Generated by Django 5.1.2 on 2024-10-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercise_difficulty_exercise_equipment_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workout',
            name='target_muscle_group',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='rest_between_exercise',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment_required',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
