# Generated by Django 5.1.2 on 2024-11-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_exercise_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='reps',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
    ]
