# Generated by Django 5.1.2 on 2024-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_exercise_reps_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
